""" add pdf report metadata

Revision ID: b722b80801a5
Revises: b7f3e9d2c1a8
Create Date: 2026-09-02 19:09:28.764644
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b722b80801a5'
down_revision: Union[str, None] = 'b7f3e9d2c1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # columns were already added in the previous failed run
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'annotated_image_path')
    op.drop_column('analyses', 'auditor_notes')
    op.drop_column('analyses', 'product_name')
    op.drop_column('analyses', 'company_name')
    # ### end Alembic commands ###
